<a href="https://colab.research.google.com/github/BralexMtz/First-AI-Algorithms/blob/main/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import torch
import numpy as np

# Trabajando con tensores.

In [2]:
torch.__version__

'1.7.1+cu101'

In [4]:
#tensor con solo unos
tensor_a=torch.ones(2,2)

tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [6]:
#tensor con variales aleatorios
tensor_b = torch.Tensor(2,2)
print(tensor_b)
# si modifica, ponemos un '_' al final
# esto modificará al tensor con valores entre 0 y 1
tensor_b.uniform_(0,1)

tensor([[-2.3436e+00,  3.0899e-41],
        [ 3.3631e-44,  0.0000e+00]])


tensor([[0.2650, 0.1576],
        [0.9894, 0.0875]])

In [8]:
# sis lo genera entre cero y uno por default
tensor_c =  torch.rand(2,2)
tensor_c

tensor([[0.3141, 0.5402],
        [0.3732, 0.6676]])

In [11]:
result= tensor_b+tensor_c
result

tensor([[0.5791, 0.6978],
        [1.3626, 0.7551]])

In [16]:
#Muy comun que se cambian las dimensiones
result.shape
#Tambien podemos cambiarlo
reshaped = result.view(4,1)
reshaped

tensor([[0.5791],
        [0.6978],
        [1.3626],
        [0.7551]])

In [20]:
# con 'tensor' en minusculas podemos definir los valores que queremos en el tensor
# Además si ponemos numeros con punto decimal decimos que son numero flotantes.
points =  torch.tensor([[1.0,2.0],[3.0,4.0]])
print(points)
points[0][1]=2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [22]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

El resultado de stride, de acuerdo a como se almacenan en memoria, nos dice el número de localidades de memoria para pasar de un renglon a otro.

In [25]:
#para transponer
pt= points.t()
#tambien cambia el stride
pt, pt.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [30]:
tensor_x =  torch.tensor([1,2,4,5])
print(tensor_x)
#se agrega una dimension(aumentamos la caja) vertical
print(torch.unsqueeze(tensor_x,1))

#se agrega una dimension horizontal
print(torch.unsqueeze(tensor_x,0))

tensor([1, 2, 4, 5])
tensor([[1],
        [2],
        [4],
        [5]])
tensor([[1, 2, 4, 5]])


In [33]:
numpyArray = np.random.randn(2,2)
#numpy a tensor
torch.from_numpy(numpyArray)

tensor([[-0.3131,  1.2771],
        [ 0.0885,  0.8000]], dtype=torch.float64)