<a href="https://colab.research.google.com/github/BralexMtz/First-AI-Algorithms/blob/main/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd

# Trabajando con tensores.

---



In [2]:
torch.__version__

'1.7.1+cu101'

In [3]:
#tensor con solo unos
tensor_a=torch.ones(2,2)

tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [4]:
#tensor con variales aleatorios
tensor_b = torch.Tensor(2,2)
print(tensor_b)
# si modifica, ponemos un '_' al final
# esto modificará al tensor con valores entre 0 y 1
tensor_b.uniform_(0,1)

tensor([[-5.5654e+30,  3.0809e-41],
        [ 3.7835e-44,  0.0000e+00]])


tensor([[0.2418, 0.8090],
        [0.6830, 0.4630]])

In [5]:
# sis lo genera entre cero y uno por default
tensor_c =  torch.rand(2,2)
tensor_c

tensor([[0.6446, 0.7606],
        [0.2961, 0.7167]])

In [6]:
result= tensor_b+tensor_c
result

tensor([[0.8864, 1.5696],
        [0.9792, 1.1797]])

In [7]:
#Muy comun que se cambian las dimensiones
result.shape
#Tambien podemos cambiarlo
reshaped = result.view(4,1)
reshaped

tensor([[0.8864],
        [1.5696],
        [0.9792],
        [1.1797]])

In [8]:
# con 'tensor' en minusculas podemos definir los valores que queremos en el tensor
# Además si ponemos numeros con punto decimal decimos que son numero flotantes.
points =  torch.tensor([[1.0,2.0],[3.0,4.0]])
print(points)
points[0][1]=2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [9]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

El resultado de stride, de acuerdo a como se almacenan en memoria, nos dice el número de localidades de memoria para pasar de un renglon a otro.

In [10]:
#para transponer
pt= points.t()
#tambien cambia el stride
pt, pt.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [11]:
tensor_x =  torch.tensor([1,2,4,5])
print(tensor_x)
#se agrega una dimension(aumentamos la caja) vertical
print(torch.unsqueeze(tensor_x,1))

#se agrega una dimension horizontal
print(torch.unsqueeze(tensor_x,0))

tensor([1, 2, 4, 5])
tensor([[1],
        [2],
        [4],
        [5]])
tensor([[1, 2, 4, 5]])


In [12]:
numpyArray = np.random.randn(2,2)
#numpy a tensor
from_numpy= torch.from_numpy(numpyArray)
from_numpy

tensor([[-0.0285, -0.7572],
        [ 1.2697,  0.2626]], dtype=torch.float64)

# Representando datos con tensores
---



In [13]:
print(from_numpy)
#se obtendrá la media de todos los elementos del tensor, devolviendo un número
print(torch.mean(from_numpy))
#con dim=0 se hará la media por cada columna.
print(torch.mean(from_numpy,dim=0))
# con dim=1 se hará la media con respecto a las filas.
print(torch.mean(from_numpy,dim=1))

tensor([[-0.0285, -0.7572],
        [ 1.2697,  0.2626]], dtype=torch.float64)
tensor(0.1866, dtype=torch.float64)
tensor([ 0.6206, -0.2473], dtype=torch.float64)
tensor([-0.3929,  0.7662], dtype=torch.float64)


In [14]:
# Calculando desviación estandar de la misma manera
torch.std(from_numpy,dim=1)
# Se guarda el tensor en un archivo tensor.t serializado
torch.save(from_numpy,'tensor.t')

In [15]:
# Así mismo podemos cargar tensores desde archivos.
load = torch.load('tensor.t')
load


tensor([[-0.0285, -0.7572],
        [ 1.2697,  0.2626]], dtype=torch.float64)

In [16]:
# cargamos con pandas un dataset

url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [17]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [18]:
subset=  dataframe[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna(axis=0,how='any') # eliminar las filas con datos nulos
# eliminar la cabecera o primera fila
columns = subset.columns[1:]
# creamos un tensor a partir de los valores, forzandolo a ser flotantes
players=torch.tensor(subset.values).float()

players.shape,players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [19]:
#Tomamos los valores sin el target de Overall(target) o variable a predecir
data = players[:,1:]
data,data.shape
#nos quedan solo las variables de entrada

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [20]:
# podemos tomar una unica columna
# para el target
target = players[:,0]
target,target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [21]:
# Sacamos la media de las variables de entrada para cada columna 
mean = torch.mean(data,dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [22]:
# Tambien podemos sacar la desviación estandar.
std= torch.std(data,dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [23]:
# podemos normalizar los datos.
norm = (data-mean)/torch.sqrt(std)
# Esto permite tener a todos los valores dentro de un mismo rango
# (Respecto a la población de cada columna)
norm 

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [24]:
#¿Cómo esto es posible?
#Filtramos el data a partir de un tensor booleano devuelto por las funciones
# ge, gt, lt, le
good = data[torch.ge(target,85)]
average = data[torch.gt(target,70) & torch.lt(target,85)]
notSoGood= data[torch.le(target,70)]


goodMean = torch.mean(good,dim=0)
averageMean = torch.mean(average,dim=0)
notSoGoodMean = torch.mean(notSoGood,dim=0)

#good(Mean, averageMean, notSoGoodMean

for i, args in enumerate(zip(columns,goodMean,averageMean,notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
